insert into public.sessions (id, program_id, title, description, question, phase, "order") values
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0001', 'foundation-30', 'How do you feel about your life right now?', 'Start small. You do not need a full life assessment here, only an honest snapshot of how things feel lately.', 'How do you feel about your life right now?', 'Land', 1),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0002', 'foundation-30', 'What has been occupying your mind lately?', 'Notice the thoughts or themes that have been showing up most lately. A few simple observations are enough.', 'What has been occupying your mind lately?', 'Land', 2),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0003', 'foundation-30', 'What drains your energy?', 'Think gently about what tends to leave you feeling drained, flat, or less like yourself.', 'What drains your energy?', 'Land', 3),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0004', 'foundation-30', 'What gives you energy?', 'Think about what tends to leave you feeling lighter, clearer, or more like yourself.', 'What gives you energy?', 'Land', 4),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0005', 'foundation-30', 'When do you feel calm?', 'Look for the moments, places, or habits that help your body and mind settle, even a little.', 'When do you feel calm?', 'Land', 5),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0006', 'foundation-30', 'When do you feel strong?', 'Reflect on the moments where you feel capable, steady, or more trusting of yourself.', 'When do you feel strong?', 'Land', 6),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0007', 'foundation-30', 'What have you noticed about yourself this week?', 'Gather what you have noticed so far, even if it still feels small, early, or unfinished.', 'What have you noticed about yourself this week?', 'Land', 7),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0008', 'foundation-30', 'What takes up most of your mental space?', 'Name the concerns, loops, or responsibilities that have been taking up the most room in your mind.', 'What takes up most of your mental space?', 'Clear', 8),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0009', 'foundation-30', 'What should you say no to?', 'Identify what is costing more than it gives back.', 'What should you say no to?', 'Clear', 9),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0010', 'foundation-30', 'What deserves more attention?', 'Bring forward what matters but keeps being postponed.', 'What deserves more attention?', 'Clear', 10),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0011', 'foundation-30', 'What do you spend most of your time on?', 'Compare your time with what you say matters.', 'What do you spend most of your time on?', 'Clear', 11),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0012', 'foundation-30', 'What makes your life more complicated than it needs to be?', 'Notice the friction you may be maintaining out of habit.', 'What makes your life more complicated than it needs to be?', 'Clear', 12),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0013', 'foundation-30', 'What decision are you avoiding?', 'Look directly at the choice you keep circling.', 'What decision are you avoiding?', 'Clear', 13),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0014', 'foundation-30', 'What clarity have you gained this week?', 'Pause and name what has become more honest or more obvious.', 'What clarity have you gained this week?', 'Clear', 14),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0015', 'foundation-30', 'What does success mean to you?', 'Define success on your own terms rather than inherited ones.', 'What does success mean to you?', 'Aim', 15),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0016', 'foundation-30', 'What do you want to be known for?', 'Reflect on the qualities and contribution you want people to associate with you.', 'What do you want to be known for?', 'Aim', 16),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0017', 'foundation-30', 'What do you want to achieve in the next three years?', 'Stretch your perspective beyond the current week and month.', 'What do you want to achieve in the next three years?', 'Aim', 17),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0018', 'foundation-30', 'What do you want to learn?', 'Name the growth that would expand your life or confidence.', 'What do you want to learn?', 'Aim', 18),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0019', 'foundation-30', 'What would you change in your life?', 'Be direct about the changes you already know you want.', 'What would you change in your life?', 'Aim', 19),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0020', 'foundation-30', 'What inspires you?', 'Look for the people, ideas, and environments that pull you forward.', 'What inspires you?', 'Aim', 20),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0021', 'foundation-30', 'What matters most right now?', 'Reduce the noise and identify the current core priority.', 'What matters most right now?', 'Aim', 21),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0022', 'foundation-30', 'What is your next step?', 'Turn reflection into something concrete and immediate.', 'What is your next step?', 'Move', 22),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0023', 'foundation-30', 'What is holding you back?', 'Name the friction, fear, or pattern that slows your movement.', 'What is holding you back?', 'Move', 23),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0024', 'foundation-30', 'What habit would help you most?', 'Think about repetition rather than motivation alone.', 'What habit would help you most?', 'Move', 24),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0025', 'foundation-30', 'What can you do today?', 'Choose the smallest meaningful action available now.', 'What can you do today?', 'Move', 25),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0026', 'foundation-30', 'What can you do this week?', 'Think one layer bigger than today without drifting into abstraction.', 'What can you do this week?', 'Move', 26),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0027', 'foundation-30', 'Who could help you move forward?', 'Bring support into the process instead of carrying everything alone.', 'Who could help you move forward?', 'Move', 27),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0028', 'foundation-30', 'What will you do differently from now on?', 'Name the change you are ready to embody, not just think about.', 'What will you do differently from now on?', 'Move', 28),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0029', 'foundation-30', 'What have you learned about yourself?', 'Look back and surface the patterns, truths, and strengths that emerged.', 'What have you learned about yourself?', 'Move', 29),
('8c7ab420-f1c5-4e93-91eb-a8f5c9cb0030', 'foundation-30', 'What do you want to take with you from this journey?', 'Close the program by choosing what remains important after reflection.', 'What do you want to take with you from this journey?', 'Move', 30)
on conflict (id) do update set
  program_id = excluded.program_id,
  title = excluded.title,
  description = excluded.description,
  question = excluded.question,
  phase = excluded.phase,
  "order" = excluded."order";
