import { SessionDefinition } from "@/lib/types";

export const FOUNDATION_30: SessionDefinition[] = [
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0001",
    programId: "foundation-30",
    phase: "Land",
    order: 1,
    title: "How do you feel about your life right now?",
    description: "Start simple. Write a few honest lines about how life feels lately, without trying to solve everything.",
    question: "How do you feel about your life right now?",
    optionalActionLabel: "One thing to notice tomorrow",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0002",
    programId: "foundation-30",
    phase: "Land",
    order: 2,
    title: "What has been occupying your mind lately?",
    description: "Notice the thoughts, worries, or themes that have been taking up space recently.",
    question: "What has been occupying your mind lately?",
    optionalActionLabel: "One thought to notice more gently",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0003",
    programId: "foundation-30",
    phase: "Land",
    order: 3,
    title: "What drains your energy?",
    description: "Think about the people, tasks, or patterns that leave you feeling flatter or more depleted.",
    question: "What drains your energy?",
    optionalActionLabel: "One drain to reduce this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0004",
    programId: "foundation-30",
    phase: "Land",
    order: 4,
    title: "What gives you energy?",
    description: "Think about what helps you feel lighter, clearer, or more like yourself.",
    question: "What gives you energy?",
    optionalActionLabel: "One energizing action to repeat tomorrow",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0005",
    programId: "foundation-30",
    phase: "Land",
    order: 5,
    title: "When do you feel calm?",
    description: "Look for the moments, places, or habits that make your body and mind slow down a little.",
    question: "When do you feel calm?",
    optionalActionLabel: "One calming condition to create this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0006",
    programId: "foundation-30",
    phase: "Land",
    order: 6,
    title: "When do you feel strong?",
    description: "Reflect on the moments where you trust yourself most.",
    question: "When do you feel strong?",
    optionalActionLabel: "One strength to lean on tomorrow",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0007",
    programId: "foundation-30",
    phase: "Land",
    order: 7,
    title: "What have you noticed about yourself this week?",
    description: "Gather what you have noticed so far, even if it feels small or unfinished.",
    question: "What have you noticed about yourself this week?",
    optionalActionLabel: "One insight to carry into next week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0008",
    programId: "foundation-30",
    phase: "Clear",
    order: 8,
    title: "What takes up most of your mental space?",
    description: "Surface the concerns, loops, or responsibilities competing for attention.",
    question: "What takes up most of your mental space?",
    optionalActionLabel: "One thing to clear from your mind",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0009",
    programId: "foundation-30",
    phase: "Clear",
    order: 9,
    title: "What should you say no to?",
    description: "Identify what is costing more than it gives back.",
    question: "What should you say no to?",
    optionalActionLabel: "One boundary to set this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0010",
    programId: "foundation-30",
    phase: "Clear",
    order: 10,
    title: "What deserves more attention?",
    description: "Bring forward what matters but keeps being postponed.",
    question: "What deserves more attention?",
    optionalActionLabel: "One area to prioritize tomorrow",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0011",
    programId: "foundation-30",
    phase: "Clear",
    order: 11,
    title: "What do you spend most of your time on?",
    description: "Compare your time with what you say matters.",
    question: "What do you spend most of your time on?",
    optionalActionLabel: "One time shift to test this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0012",
    programId: "foundation-30",
    phase: "Clear",
    order: 12,
    title: "What makes your life more complicated than it needs to be?",
    description: "Notice the friction you may be maintaining out of habit.",
    question: "What makes your life more complicated than it needs to be?",
    optionalActionLabel: "One thing to simplify this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0013",
    programId: "foundation-30",
    phase: "Clear",
    order: 13,
    title: "What decision are you avoiding?",
    description: "Look directly at the choice you keep circling.",
    question: "What decision are you avoiding?",
    optionalActionLabel: "One next move toward that decision",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0014",
    programId: "foundation-30",
    phase: "Clear",
    order: 14,
    title: "What clarity have you gained this week?",
    description: "Pause and name what has become more honest or more obvious.",
    question: "What clarity have you gained this week?",
    optionalActionLabel: "One clarity statement to keep visible",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0015",
    programId: "foundation-30",
    phase: "Aim",
    order: 15,
    title: "What does success mean to you?",
    description: "Define success on your own terms rather than inherited ones.",
    question: "What does success mean to you?",
    optionalActionLabel: "One way to measure success differently",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0016",
    programId: "foundation-30",
    phase: "Aim",
    order: 16,
    title: "What do you want to be known for?",
    description: "Reflect on the qualities and contribution you want people to associate with you.",
    question: "What do you want to be known for?",
    optionalActionLabel: "One trait to express more clearly this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0017",
    programId: "foundation-30",
    phase: "Aim",
    order: 17,
    title: "What do you want to achieve in the next three years?",
    description: "Stretch your perspective beyond the current week and month.",
    question: "What do you want to achieve in the next three years?",
    optionalActionLabel: "One milestone to define next",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0018",
    programId: "foundation-30",
    phase: "Aim",
    order: 18,
    title: "What do you want to learn?",
    description: "Name the growth that would expand your life or confidence.",
    question: "What do you want to learn?",
    optionalActionLabel: "One learning step to begin this month",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0019",
    programId: "foundation-30",
    phase: "Aim",
    order: 19,
    title: "What would you change in your life?",
    description: "Be direct about the changes you already know you want.",
    question: "What would you change in your life?",
    optionalActionLabel: "One change to start shaping now",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0020",
    programId: "foundation-30",
    phase: "Aim",
    order: 20,
    title: "What inspires you?",
    description: "Look for the people, ideas, and environments that pull you forward.",
    question: "What inspires you?",
    optionalActionLabel: "One source of inspiration to revisit",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0021",
    programId: "foundation-30",
    phase: "Aim",
    order: 21,
    title: "What matters most right now?",
    description: "Reduce the noise and identify the current core priority.",
    question: "What matters most right now?",
    optionalActionLabel: "One way to protect that priority tomorrow",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0022",
    programId: "foundation-30",
    phase: "Move",
    order: 22,
    title: "What is your next step?",
    description: "Turn reflection into something concrete and immediate.",
    question: "What is your next step?",
    optionalActionLabel: "Your next step in one sentence",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0023",
    programId: "foundation-30",
    phase: "Move",
    order: 23,
    title: "What is holding you back?",
    description: "Name the friction, fear, or pattern that slows your movement.",
    question: "What is holding you back?",
    optionalActionLabel: "One barrier to reduce this week",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0024",
    programId: "foundation-30",
    phase: "Move",
    order: 24,
    title: "What habit would help you most?",
    description: "Think about repetition rather than motivation alone.",
    question: "What habit would help you most?",
    optionalActionLabel: "A habit cue to test tomorrow",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0025",
    programId: "foundation-30",
    phase: "Move",
    order: 25,
    title: "What can you do today?",
    description: "Choose the smallest meaningful action available now.",
    question: "What can you do today?",
    optionalActionLabel: "Today's concrete action",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0026",
    programId: "foundation-30",
    phase: "Move",
    order: 26,
    title: "What can you do this week?",
    description: "Think one layer bigger than today without drifting into abstraction.",
    question: "What can you do this week?",
    optionalActionLabel: "This week's focus",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0027",
    programId: "foundation-30",
    phase: "Move",
    order: 27,
    title: "Who could help you move forward?",
    description: "Bring support into the process instead of carrying everything alone.",
    question: "Who could help you move forward?",
    optionalActionLabel: "One person to reach out to",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0028",
    programId: "foundation-30",
    phase: "Move",
    order: 28,
    title: "What will you do differently from now on?",
    description: "Name the change you are ready to embody, not just think about.",
    question: "What will you do differently from now on?",
    optionalActionLabel: "One promise to yourself",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0029",
    programId: "foundation-30",
    phase: "Move",
    order: 29,
    title: "What have you learned about yourself?",
    description: "Look back and surface the patterns, truths, and strengths that emerged.",
    question: "What have you learned about yourself?",
    optionalActionLabel: "One lesson to keep close",
  },
  {
    id: "8c7ab420-f1c5-4e93-91eb-a8f5c9cb0030",
    programId: "foundation-30",
    phase: "Move",
    order: 30,
    title: "What do you want to take with you from this journey?",
    description: "Close the program by choosing what remains important after reflection.",
    question: "What do you want to take with you from this journey?",
    optionalActionLabel: "One thing to carry forward",
  },
];

export const PHASE_ORDER = ["Land", "Clear", "Aim", "Move"];
